language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: true`
script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("SOFA"; coverage=true)'
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'  
